### ISSUE TITLE
Issues in documentation

### ISSUE THREAD

**Issue by jpmckinney** [OpenDataServices/flatten-tool#253]
I'll update this issue as I identify more, while reading the docs.

## All

* [x] Typos #257
* [x] Backticks #258 (builds on #257)
* [x] Other grammar and factual fixes (builds on #258)

## examples.rst

* [ ] [Arrays with arrays](https://flatten-tool.readthedocs.io/en/latest/examples/#arrays-within-arrays) seems like it was started but abandoned

## flatten.rst

* [x] Refers to default output name as `flatten` but it's `flattened` #256
* [x] "You can’t use –use-titles with flatten.", but you can #259

**Comment by jpmckinney** [comment]
> Whilst JSON pointer is designed as a way for getting data out of a JSON document, Flatten Tool uses JSON Pointer as a way of describing how to move values into a JSON document from a spreadsheet.

This isn't quite true. JSON Pointer is simply a "string syntax for identifying a specific value" in JSON. Whether the identified value is extracted or inserted – JSON Pointer has no opinion.

**Comment by jpmckinney** [comment]
@odscjames Given that the documentation is actively being edited, I'm concerned that my four PRs (linked above) will be put in conflict. I don't think any of them should be controversial or long to review.

**Comment by jpmckinney** [comment]
https://flatten-tool.readthedocs.io/en/latest/examples/#arrays-within-arrays is still incomplete, but closing as this is no longer an issue for me (feel free to re-open a new issue).
